### ISSUE TITLE
Unable to build the code without a compiler

### ISSUE THREAD

**Issue by sanojsubran** [kelseyhightower/nocode#1233]

**Comment by remindbg** [comment]
import compiler 


Done

**Comment by sanojsubran** [comment]
Tried. But compiler cannot produce no object code for no architecture. Issue not resolved.
